### ISSUE TITLE
Documents required

### ISSUE THREAD

**Issue by timhughes** [jhnnsrs/turms#21]
It appears that "documents" is required in the config and cannot be null. I am relatively new to what documents are and I am having difficulty understanding their purpose. I have a full schema and an unaware of what the requirements is for documents.

**Comment by jhnnsrs** [comment]
Hey Tim!

In general there are two different kind of way of generating graphql types with turms:

## Schema based
One is generating types from the schema (introspected or local), so that you will have enums, inputs,
and graphql objects/interfaces corresponding to the definitions in the schema. Plugins that generate
these types are

- turms.plugins.enums.EnumsPlugin
- turms.plugins.inputs.InputsPlugin
- turms.plugins.objects.ObjectsPlugin (currently only on the dev branch)

These types only take the schema as an input.

## Documents based

Documents are files that specify operations and fragments. Operations and Fragments specify a way of
querying data on the backend and generally are client specific. 

```gql

fragment UserNameID on User {
  id
  name 
}

mutation TestMutation($id: ID, $name: String) {
  insert_user(id:  $id, name $name) {
  ...UserNameID        
    }
}
```

Would be an example of a document.

When using a plugin that generated operations and fragment types, these types will **only** contain
fields for the types specified in the specific operation / fragments (as opposed to every field on the type).

Plugins that act on documents are:
- turms.plugins.fragments.FragmentsPlugin
- turms.plugins.operations.OperationsPlugin
- turms.plugin.funcs.FuncsPlugin (for generating typed functions according to the operation)

If you only want to generate types for a schema. and don't have documents, you dont need to set the documents
but then you can only use the schema plugins.

```yaml
projects:
  default:
    schema: https://countries.trevorblades.com/
    extensions:
      turms:
        out_dir: examples/api
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.inputs.InputsPlugin
          - type: turms.plugins.objects.ObjectsPlugin
        scalar_definitions:
          uuid: str
          ID: str
```

This should generate only types. (again Objects are right now only on the dev branch)
Hope that answers your question? :)
