### ISSUE TITLE
Using only `InputsPlugin` and `EnumsPlugin` generates to much code

### ISSUE THREAD

**Issue by j-riebe** [jhnnsrs/turms#4]
## Problem
The code-generation produces to much output if you're only interested in generating input types and enums.
The result isn't syntactically wrong, but not quite beautiful pydantic code.

Note: I overwrote the input-type base to generate code, that doesn't require `turms` installed in the final environment.

### Project layout
```
| - graphql.config.yaml
|
| - graphql
|   | - schema.graphql
|
| - generated
|   | - types.py

```

### `graphql.config.yaml`
```yaml
projects:
  default:
    schema: /graphql/**/*.graphql
    documents: graphql/**.graphql
    extensions:
      turms:
        out_dir: /generated
        generated_name: types.py
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.inputs.InputsPlugin
            inputtype_bases:
              - "pydantic.BaseModel"
        processors:
          - type: turms.processor.black.BlackProcessor
```

### `schema.graphql`
```graphql
type Query {
    hello(orderBy: HelloWorldOrder! = ASC, filter: HelloWorldFilter,
        first: Int, last: Int, before: String, after: String): [World!]!
}

enum HelloWorldOrder {
    ASC
    DESC
}

input HelloWorldFilter {
    search: String!
}

type World {
    message: String!
}
```

### `types.py`
```python
from turms.types.object import GraphQLObject              # <-- not required
from turms.types.object import GraphQLObject              # <-- duplicate
from pydantic.fields import Field                         # <-- not required
from typing import Optional, List, Dict, Union, Literal   # Dict, Union and Literal not required
from enum import Enum
from pydantic import BaseModel


class HelloWorldOrder(str, Enum):
    None                                   # <-- Unused statement
    ASC = "ASC"
    DESC = "DESC"


class HelloWorldFilter(BaseModel):
    None                                   # <-- Unused statement
    ids: Optional[List[str]]

```

### `types.py`
```python
from typing import Optional, List
from enum import Enum
from pydantic import BaseModel


class HelloWorldOrder(str, Enum):
    ASC = "ASC"
    DESC = "DESC"


class HelloWorldFilter(BaseModel):
    ids: Optional[List[str]]
```
