### ISSUE TITLE
Accept headers on schema

### ISSUE THREAD

**Issue by idank** [jhnnsrs/turms#50]
It seems turms doesn't allow arbitrary headers in the schema specification:

https://the-guild.dev/graphql/config/docs/user/schema#passing-headers

I do see bearer token is allowed, but the Shopify API uses a different header.

Here's what I tried:

```
projects:
  default:
    schema:
      - https://laserkaltest.myshopify.com/api/2022-10/graphql.json:
        headers:
          X-Shopify-Storefront-Access-Token: redacted
    documents: graphql/**/*.graphql
...
```
