### ISSUE TITLE
Camel case arguments are not working with Func plugin

### ISSUE THREAD

**Issue by DGolubets** [jhnnsrs/turms#63]
Hi,

It seems that there is some inconsistency in arguments casing when using the Func plugin.

I use the following config:
```
projects:
  images:
    schema: ---
    documents: queries/*.graphql
    extensions:
      turms:
        out_dir: api
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.inputs.InputsPlugin
          - type: turms.plugins.fragments.FragmentsPlugin
          - type: turms.plugins.operations.OperationsPlugin
          - type: turms.plugins.funcs.FuncsPlugin
            global_args:
              - type: gql.client.AsyncClientSession
                key: client
            definitions:
              - type: query
                use: api.proxies.execute
                is_async: True
              - type: mutation
                use: api.proxies.execute
                is_async: True
        stylers:
          - type: turms.stylers.capitalize.CapitalizeStyler
          - type: turms.stylers.snake_case.SnakeCaseStyler
        scalar_definitions:
          ID: str
          Long: int
          Instant: datetime.datetime
```

I got this Arguments class generated:
```
class Arguments(BaseModel):
        user_id: str
```
But my query uses `$userId`.
