### ISSUE TITLE
[BUG] GraphQL `type`s not being generated 

### ISSUE THREAD

**Issue by jakevollkommer** [jhnnsrs/turms#76]
Using a minimum configration, I can't get the `type` to generate pydantic classes in the output file.

`graphql.config.yml`
```
projects:
  default:
    schema: ./schema.graphql
    extensions:
      turms:
        out_dir: api
        stylers:
          - type: turms.stylers.capitalize.CapitalizeStyler
          - type: turms.stylers.snake_case.SnakeCaseStyler
        plugins:
          - type: turms.plugins.enums.EnumsPlugin
          - type: turms.plugins.inputs.InputsPlugin
        processors:
          - type: turms.processors.black.BlackProcessor
          - type: turms.processors.isort.IsortProcessor
        scalar_definitions:
          ID: str
```

`schema.graphql`
```
type TestType {
  id: ID
  name: String
}

input TestInput {
  name: String
}
```

`api/schema.py`
```
from enum import Enum
from typing import Optional

from pydantic import BaseModel


class TestInput(BaseModel):
    name: Optional[str]
```

As you can see, I get enums and inputs, but no types.

More info:
```
    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,2
      Model Number: Z14X000EUX/A
      Chip: Apple M1 Max
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 64 GB
      System Firmware Version: 10151.101.3
      OS Loader Version: 10151.101.3
      Serial Number (system): H62X42Y6FC
      Hardware UUID: 479FB683-C073-5D5F-BE74-F93305B60B53
      Provisioning UDID: 00006001-000240691144801E
      Activation Lock Status: Enabled
```
`Python 3.12.3`
`turms 0.5.0`
`pydantic 1.10.16`
`pydantic_core 2.18.2`
`graphql-core 3.2.3`
`black 24.4.2`
`isort 5.13.2`
